### ISSUE TITLE
Syntax error in generated assertion for @param {function}

### ISSUE THREAD

**Issue by victor-homyakov** [azu/jsdoc-to-assert#11]
```
    /**
     * @param {function} f
     * @return {function}
     */
    wrapHandler(f) {
```

Generated assertion has syntax error:  `typeof function !== "function"`

**Comment by azu** [comment]
fixed in [2.7.1](https://github.com/azu/jsdoc-to-assert/releases/tag/2.7.1 "2.7.1").
